name: AMchat
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.11.17=py310h06a4308_0
  - cffi=1.16.0=py310h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.3=py310hdda0065_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.101=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - numpy=1.26.2=py310h5f9d8c6_0
  - numpy-base=1.26.2=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py310h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - pytorch=2.0.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.0.2=py310_cu117
  - torchtriton=2.0.0=py310
  - torchvision=0.15.2=py310_cu117
  - typing_extensions=4.7.1=py310h06a4308_0
  - urllib3=1.26.18=py310h06a4308_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - accelerate==0.26.1
      - addict==2.4.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - aliyun-python-sdk-core==2.14.0
      - aliyun-python-sdk-kms==2.16.2
      - altair==5.2.0
      - annotated-types==0.6.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - bitsandbytes==0.42.0
      - blinker==1.7.0
      - cachetools==5.3.2
      - click==8.1.7
      - contourpy==1.2.0
      - crcmod==1.7
      - cycler==0.12.1
      - datasets==2.16.1
      - deepspeed==0.13.1
      - dill==0.3.7
      - distro==1.9.0
      - einops==0.7.0
      - et-xmlfile==1.1.0
      - fonttools==4.47.2
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - func-timeout==4.3.5
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.41
      - hjson==3.1.0
      - huggingface-hub==0.20.3
      - importlib-metadata==6.11.0
      - jmespath==0.10.0
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lagent==0.1.3
      - markdown-it-py==3.0.0
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - mmengine==0.10.3
      - modelscope==1.11.1
      - mpi4py-mpich==3.1.2
      - multidict==6.0.4
      - multiprocess==0.70.15
      - ninja==1.11.1.1
      - opencv-python==4.9.0.80
      - openpyxl==3.1.2
      - openxlab==0.0.32
      - oss2==2.17.0
      - packaging==23.2
      - pandas==2.2.0
      - peft==0.8.1
      - pillow==9.5.0
      - platformdirs==4.2.0
      - protobuf==4.25.2
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pycryptodome==3.20.0
      - pydantic==2.6.0
      - pydantic-core==2.16.1
      - pydeck==0.8.1b0
      - pygments==2.17.2
      - pympler==1.0.1
      - pynvml==11.5.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.4
      - pytz-deprecation-shim==0.1.0.post0
      - pyyaml==6.0.1
      - referencing==0.33.0
      - regex==2023.12.25
      - requests==2.28.2
      - rich==13.4.2
      - rpds-py==0.17.1
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.4.2
      - scipy==1.12.0
      - sentencepiece==0.1.99
      - setuptools==60.2.0
      - simplejson==3.19.2
      - six==1.16.0
      - smmap==5.0.1
      - sortedcontainers==2.4.0
      - streamlit==1.24.0
      - tenacity==8.2.3
      - termcolor==2.4.0
      - tiktoken==0.5.2
      - tokenizers==0.15.1
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.1
      - tornado==6.4
      - tqdm==4.65.2
      - transformers==4.37.2
      - transformers-stream-generator==0.0.4
      - tzdata==2023.4
      - tzlocal==4.3.1
      - validators==0.22.0
      - watchdog==3.0.0
      - xxhash==3.4.1
      - yapf==0.40.2
      - yarl==1.9.4
      - zipp==3.17.0
